### ISSUE TITLE
Client fails to fetch data from API

### ISSUE THREAD

**Issue by joe-mills** [staticwebdev/blazor-starter#29]
Hi,

I've run through the getting started steps on VS 2022 and VS Code with Azure Static Web App CLI on two separate machines and the Fetch Data request fails on the client each time on the following line

    forecasts = await Http.GetFromJsonAsync<WeatherForecast[]>("/api/WeatherForecast") ?? new WeatherForecast[]{};

Using the debugger I can see that the request is successfully sent to the API endpoint and the function returns the data correctly.

The exception on the client is as follows

System.Net.Http.HttpRequestException: TypeError: Failed to fetch
 ---> System.Runtime.InteropServices.JavaScript.JSException: TypeError: Failed to fetch
   at System.Net.Http.BrowserHttpHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.BrowserHttpHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at System.Net.Http.Json.HttpClientJsonExtensions.<GetFromJsonAsyncCore>d__13`1[[BlazorApp.Shared.WeatherForecast[], Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at BlazorApp.Client.Pages.FetchData.OnInitializedAsync() in C:\source\blazorstaticdemo\blazorstaticdemo\Client\Pages\FetchData.razor:line 45

**Comment by joe-mills** [comment]
oops, missed step 2 of getting started - my bad

In the Api folder, copy local.settings.example.json to local.settings.json
